Add some more EntityModules and Features
SandboxPowered/SandboxAPI pull request #32
Opened 2020-08-06 18:23 UTC by WolfShotz

Also adds the following:
+ DamageSource
+ SoundEvent and SoundCategory

2020-08-06 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SandboxPowered/SandboxAPI?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SandboxPowered/SandboxAPI?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SandboxPowered/SandboxAPI?pullRequest=32) it.</sub>

2020-08-06 19:01 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isInWater();
is this "touching water" or "fully submerged in water"?

2020-08-06 19:02 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    void markVelocityUpdate();
this should be `queueVelocitySync()`

2020-08-06 19:03 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +                return true;
If you return early here, this is just an event with extra steps.

2020-08-06 19:03 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/LivingEntity.java
> +            if (module.getKey().onDeath(Entity.cast(module.getValue()), cause)) return;
If you return early here, this is just an event with extra steps.

2020-08-06 19:07 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +public class AgeableEntityModule implements EntityModule<AgeableEntityModule> {
maybe make this `Breedable` instead of `Ageable`?
Or better, split aging and breeding into different modules

2020-08-06 19:09 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +    private static final String BREEDER_KEY = "LoveCause"; // vanilla
Sandbox API should not need to know about implementation details.

2020-08-06 19:13 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/SoundEntityModule.java
> +    public void resetSoundTime() {
this resets the sound *chance*, not some timer.

2020-08-06 19:21 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/util/DamageSource.java
> +    public Entity getAttackingProjectile() {
this is not necessarily a projectile, just vanilla only uses it for that.
name it `getCause()`.
Also make it `@Nullable`

2020-08-06 19:21 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/util/DamageSource.java
> +    public Entity getAttackingEntity() {
should be `getAttacker()`, the `entity` part doesn't add informational value.
also make it `@Nullable`

2020-08-06 19:24 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/util/SoundEvent.java
> +public class SoundEvent {
naming it `Event` might be confusing since we have an actual event api.
Make it just `Sound`.

2020-08-06 19:26 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    void markVelocityUpdate();
Is this needed? why not just have the setVelocity method trigger that?

2020-08-06 19:28 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +    private final List<Item> foodItems = new ArrayList<>();
This has no reason to be an ArrayList. It should be a HashSet

2020-08-06 19:29 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/SoundEntityModule.java
> +    public SoundEntityModule(LivingEntity entity) {
Assuming this is only for LivingEntity and casting probably isn't the best idea for an ECS

2020-08-06 19:30 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/WaterEntityModule.java
> +public class WaterEntityModule implements EntityModule<LivingEntity> {
this is not a "water module", but rather one that handles entities being able to drown in water, and should be named accordingly

2020-08-06 19:31 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/SoundEntityModule.java
> +    private static final SyncedData<Boolean> SILENT = DataManager.register(Identity.of("sandbox", "silent"), DataSerializers.BOOLEAN);
Maybe flip the order of these 2 fields?

2020-08-06 19:32 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/SoundEntityModule.java
> +        if (instance.entity.isAlive() && instance.entity.getRandom().nextInt(1000) < ambientSoundChance++) {
`ambientSoundChance` should be a double used with `getRandom().nextDouble()` instead of an integer

2020-08-06 19:33 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/SoundEntityModule.java
> +    public boolean attackFrom(SoundEntityModule instance, DamageSource source, float amount) {
Overrides that don't change the value should return super

2020-08-06 19:34 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/EntityModule.java
> +    default boolean attackFrom(T instance, DamageSource source, float amount) { return false; }
Shouldn't the default value of these be true so it doesn't affect the default handling?

2020-08-06 19:44 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/util/SoundEvent.java
> +public class SoundEvent {
Or maybe `SoundType`, as that's pretty much what it's used as in vanilla, while `Sound` is more the sound object that the game plays

2020-08-06 19:57 UTC, WolfShotz commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +public class AgeableEntityModule implements EntityModule<AgeableEntityModule> {
My initial thought was to split them, though the problem is they would depend on each other in a handful of scenarios, so I ended up just merging them. I will split them and see what you think

2020-08-06 21:16 UTC, WolfShotz commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    void markVelocityUpdate();
Its how its done in vanilla

2020-08-06 21:51 UTC, WolfShotz commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +public class AgeableEntityModule implements EntityModule<AgeableEntityModule> {
Split into two modules.

2020-08-07 12:05 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +        if (player != null) this.breeder = player.getPersistentID();
need to reset the field if player is null

2020-08-07 12:05 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +    private UUID breeder;
should be `@Nullable`

2020-08-07 12:06 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +    private static final String BREEDER_KEY = "LoveCause";
again: Sandbox API should not care about serialization. This should be in game-specific implementations instead.

2020-08-07 12:10 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +            if (player.getWorld().isServer() && instance.canBreed()) {
server and client shouldn't have different return values

2020-08-07 12:12 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/WaterBreathingEntityModule.java
> +            entity.setAir(--prev);
what is the point of decrementing `prev` here? just pass `prev - 1`

2020-08-07 12:14 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/WaterBreathingEntityModule.java
> +        else entity.setAir(300);
this shouldn't be hardcoded. for now simply add a todo comment.

2020-08-07 12:16 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isTouchingWater();
Looking at your implementation, you probably meant the entity being submerged? Why should an Entity suffocate if only its feet are inside water?

2020-08-07 12:18 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +            else if (prev > 0) instance.ageUp(--prev);
so if the previous age is `0`, it won't update ever again?
also no need to increment/decrement `prev` inline here, just pass `prev + 1` / `prev - 1` respectively.

2020-08-07 12:19 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +            instance.ageUp((int) ((-instance.getAge() / 20) * 0.1f));
`getAge() / 20` is an integer division, is that intended?

2020-08-07 12:21 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +        if (prev < 0 && age >= 0 || prev >= 0 && age < 0) entity.getDataManager().set(CHILD, age < 0);
this can be simplified to `(prev < 0) != (age < 0)`

2020-08-07 12:22 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +                .orElse(false);
this should fall back to `true` if no age module was found.

2020-08-07 12:25 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/util/DamageSource.java
> +        return entity.getType() == EntityTypes.PLAYER.get() && ((PlayerEntity) entity).isCreativeMode();
getAtttacker() is nullable, so maybe replace the type check with an instanceof.

2020-08-07 12:27 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    default boolean isTouchingWaterOrBubbleColumn() {
see my comment on `isTouchingWater()`

2020-08-08 01:46 UTC, WolfShotz commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/AgeableEntityModule.java
> +            else if (prev > 0) instance.ageUp(--prev);
thats true. an age of 0 is an adult. However, the value should *never* be over 0. If its below it, its simply a child. If its over 0, then just decrement down. Simply following vanilla logic

2020-08-25 13:25 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/BreedableEntityModule.java
> +                .orElse(false);
It does default to true, the optional module returns false if the entity isn't a child or the module isn't present, which is then negated meaning it's true.

2020-08-30 17:08 UTC, MsRandom requested changes

2020-08-30 17:08 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    default EntityModule addModule(EntityModule.Type<?> module) {
Don't return `EntityModule`, return a generic `T` which extends `EntityModule` and make module an `EntityModule.Type<T>`.

2020-08-30 17:08 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/util/DamageSource.java
> +public class DamageSource {
This should be an interface so it can be implemented.

2020-08-30 17:08 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/util/SoundCategory.java
> +public class SoundCategory {
Should be an interface.

2020-08-30 22:04 UTC, MsRandom approved these changes

2020-09-09 01:42 UTC, MsRandom commented
Note: this pr also includes changes to the API itself that I made here instead of in the original branch.

2020-09-16 15:27 UTC, TheCodedOne requested changes

2020-09-16 15:27 UTC, TheCodedOne commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isSubmergedInWater();
is this specific to water or is it actually submerged in any fluid? if the latter it should be named `isSubmerged`
```suggestion
    boolean isSubmerged();
```

2020-09-20 16:18 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isSubmergedInWater();
I think the vanilla one just checks water, maybe we should have a `isSubmerged(Fluid)` method to be more generic?

2020-10-03 11:07 UTC, TheCodedOne commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isSubmergedInWater();
Could do

2020-10-04 21:42 UTC, TheCodedOne requested changes

2020-10-04 21:42 UTC, TheCodedOne commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isSubmerged(Fluid fluid);
There should be a method which also accepts `Entry<Fluid>` for easier `isSubmerged(Fluids.WATER)`ness

2020-10-04 21:44 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/Entity.java
> +    boolean isSubmerged(Fluid fluid);
Alright

2020-10-05 11:05 UTC, TheCodedOne approved these changes

2020-10-06 07:14 UTC, UpcraftLP requested changes

2020-10-06 07:14 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/TameableEntityModule.java
> +        if (data == TAMEABLE_DATA) return (byte) 0;
maybe cast to `Byte` instead, to save one step of auto-boxing.

2020-10-06 07:14 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/state/BlockState.java
> +
fix this please.

2020-10-06 07:39 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/TameableEntityModule.java
> +        if (data == TAMEABLE_DATA) return (byte) 0;
You can't cast `0` to `Byte`, so I'd have to do `Byte.valueOf((byte) 0)`, and I don't really see a reason to do that

2020-10-06 14:39 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/entity/module/TameableEntityModule.java
> +        if (data == TAMEABLE_DATA) return (byte) 0;
sorry, my bad

2020-10-06 14:40 UTC, UpcraftLP requested changes

2020-10-06 14:40 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/state/BlockState.java
> +
there's still some spaces here that should be removed

2020-10-06 19:00 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/state/BlockState.java
> +
that's just a newline on the end I'm pretty sure

2020-10-07 03:14 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/state/BlockState.java
> +
I removed it, although I prefer having it as the end but regardless that's fixed now

2020-10-07 10:11 UTC, MsRandom commented on modules/base/src/main/java/org/sandboxpowered/api/state/BlockState.java
> +
Wait hold up, I only saw what you meant just now lol, I'll fix it

2020-10-07 14:28 UTC, UpcraftLP approved these changes

2020-10-07 14:28 UTC, merged