Start UI API
SandboxPowered/SandboxAPI pull request #34
Opened 2020-08-28 10:14 UTC by TheCodedOne

2020-09-01 22:02 UTC, UpcraftLP requested changes

2020-09-02 13:39 UTC, UpcraftLP approved these changes

2020-09-02 21:05 UTC, UpcraftLP approved these changes

2020-09-11 15:51 UTC, UpcraftLP approved these changes

2020-09-16 06:57 UTC, MsRandom approved these changes

2020-09-16 11:41 UTC, UpcraftLP approved these changes

2020-10-26 02:34 UTC, Boundarybreaker approved these changes
Looks mostly good, might have to do a closer inspection of the new resource stuff

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/base/src/main/java/org/sandboxpowered/api/registry/Registry.java
> +    Entry<T> register(T val);
If we're going this way, should we do a `registerAll`?

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/base/src/main/java/org/sandboxpowered/api/server/Server.java
>  }
add LF

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/base/src/main/java/org/sandboxpowered/api/tags/Tag.java
> +}
LF

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/base/src/main/java/org/sandboxpowered/api/tags/Tag.java
> +    Stream<C> values();
Streams are kinda slow sadly, maybe `Collection<C>` instead?

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/base/src/main/java/org/sandboxpowered/api/world/WorldReader.java
>  }
LF

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/rendering/src/main/java/org/sandboxpowered/api/client/rendering/ui/DynamicRenderer.java
> +public interface DynamicRenderer {
None of the sprite-render stuff here seems to support UVs, so they'll always start drawing from the top-left of the sprite.

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/Resource.java
> +}
LF

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceMaterial.java
> +}
LF

2020-10-26 02:34 UTC, Boundarybreaker commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceService.java
> +}
LF

2020-10-27 18:15 UTC, TheCodedOne commented on modules/base/src/main/java/org/sandboxpowered/api/tags/Tag.java
> +    Stream<C> values();
Streams are used instead of collections as if we made it a collection it'd have to stream then collect, & if someone streams that again, its just pointless. if people need a collection they can collect it.

2020-12-17 13:29 UTC, UpcraftLP requested changes

2020-12-17 13:29 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/block/Block.java
> +     * Make sure to return true {@link Block#hasBlockEntity(BlockState)} to use this
where'd the `in` go

2020-12-17 13:29 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/util/Log.java
> +    void info(String message, Object... args);
might as well get rid of the overloads without vararg

2020-12-17 13:29 UTC, UpcraftLP commented on modules/base/src/main/java/org/sandboxpowered/api/world/WorldReader.java
> +    long getWorldTime();
should probably add some javadoc comment clarifying world time vs time of day?

2020-12-17 13:29 UTC, UpcraftLP commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceConstants.java
> +}
newline for consistency

2020-12-17 13:29 UTC, UpcraftLP commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceMaterial.java
> +        this.id = Objects.requireNonNull(id);
should add an error message to the `requireNonNull()` call

2020-12-17 13:29 UTC, UpcraftLP commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceService.java
> +    void add(ResourceMaterial material, ResourceType<?>... types);
should probably be `ResourceType<? extends Content<?>>`

2020-12-17 13:29 UTC, UpcraftLP commented on modules/resources/src/main/java/org/sandboxpowered/api/resources/ResourceService.java
> +    <C extends Content<C>> void add(ResourceMaterial material, ResourceType<C> type);
this overload is probably not needed, due to the vararg.

2021-01-15 15:44 UTC, closed without merging